AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ONNX-MobileNet-Inference

  Sample SAM Template for ONNX-MobileNet-Inference

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  ONNXMobileNetFunctionPackageBasedTest:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # PackageType: Image
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    # Metadata:
    #   Dockerfile: Dockerfile
    #   DockerContext: ./
    #   DockerTag: v1.0

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ONNXMobileNetFunctionPackageBasedTestApi:
    Description: "API Gateway endpoint URL for Prod stage for ONNXMobileNetFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ONNXMobileNetFunctionPackageBasedTest:
    Description: "ONNXMobileNetFunction Lambda Function ARN"
    Value: !GetAtt ONNXMobileNetFunctionPackageBasedTest.Arn
  ONNXMobileNetFunctionPackageBasedTestIamRole:
    Description: "Implicit IAM Role created for ONNXMobileNetFunction function"
    Value: !GetAtt ONNXMobileNetFunctionPackageBasedTestRole.Arn
