version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ONNX-SqueezeNet-S3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7b4id1xqt28h"
s3_prefix = "ONNX-SqueezeNet-S3"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
