version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ONNX-ResNet-Inference"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7b4id1xqt28h"
s3_prefix = "ONNX-ResNet-Inference"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["ONNXResNetFunctionContainerBasedTest=235319806087.dkr.ecr.ap-south-1.amazonaws.com/onnxresnetinference7115c1d8/onnxresnetfunctioncontainerbasedtest87afc928repo"]
