AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ONNX-ResNet-Inference

  Sample SAM Template for ONNX-ResNet-Inference

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  ONNXResNetFunctionContainerBasedTest:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: v1.0

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ONNXResNetFunctionContainerBasedTestApi:
    Description: "API Gateway endpoint URL for Prod stage for ONNXResNetFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ONNXResNetFunctionContainerBasedTest:
    Description: "ONNXResNetFunction Lambda Function ARN"
    Value: !GetAtt ONNXResNetFunctionContainerBasedTest.Arn
  ONNXResNetFunctionContainerBasedTestIamRole:
    Description: "Implicit IAM Role created for ONNXResNetFunction function"
    Value: !GetAtt ONNXResNetFunctionContainerBasedTestRole.Arn
