version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ONNX-Resize"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7b4id1xqt28h"
s3_prefix = "ONNX-Resize"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["ONNXResizeFunctionContainerBasedTest=235319806087.dkr.ecr.ap-south-1.amazonaws.com/onnxresizeb8c3b546/onnxresizefunctioncontainerbasedtest0ac4c712repo"]
